version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        - "./rabbitmq_delayed_message_exchange-3.12.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez"
        - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
        # - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
